notifications:
  email: false

branches:
  only:
    - master

# travis will pick the Node.js version from the .nvmrc
language: node_js
cache:
  directories:
    - "node_modules"

before_script:
  - npm prune
script:
  - npm run lint
  - npm run test -- --ci
